import { SMOKE_TYPES } from '../../behaviors/smoke'

export const BASE = {
  score: 25,
  health: 20,
  frame: 0,
  scale: 2,
  speed: 400,
  turnRate: 4,
  avoidRadius: 50,
  wobbleLimit: 20,
  wobbleSpeed: 450,
  stallTimeout: 120,
  stallDuration: 2000,
  stallRecharge: 3000,
  explosionDelay: 0,
  triggerRadius: 100,
  size: 30,
  explosionRadius: 100,
  explosionDamage: 20,
  smoke: SMOKE_TYPES.normal,
}

export const TYPES = {
  normal: {
    ...BASE,
  },
  fast: {
    ...BASE,
    speed: 700,
    frame: 3,
    scale: 1,
    health: 10,
    score: 50,
    turnRate: 10,
    triggerRadius: 50,
    explosionRadius: 50,
    explosionDamage: 20,
    smoke: SMOKE_TYPES.fast,
  },
  big: {
    ...BASE,
    explosionDamage: 34,
    speed: 250,
    frame: 1,
    health: 60,
    turnRate: 1.7,
    scale: 4,
    score: 100,
    wobbleLimit: 35,
    wobbleSpeed: 2000,
    stallTimeout: 300,
    triggerRadius: 100,
    explosionRadius: 200,
    avoidRadius: 100,
    smoke: SMOKE_TYPES.big,
  },
}
